version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: sh -c "CHOKIDAR_USEPOLLING=true npm start"
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=realworld-docker.local
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=80
      - WDS_SOCKET_PATH=/sockjs-node
    volumes:
      - ./frontend:/user/src/app
      - /user/src/app/node_modules

  api:
    command: npm run dev
    volumes:
      - ./api/src:/user/src/app/src
      - /user/src/app/node_modules

  auth:
    command: npm run dev
    volumes:
      - ./auth/src:/user/src/app/src
      - /user/src/app/node_modules

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
